const stages=[
 {title:'辺境の狼煙',roman:'I',story:'グラナ辺境に帝国軍の狼煙が上がった。若き騎士アルドは、故郷を守るため初めての剣を抜く。',objective:'敵軍をすべて撃破',terrain:'plains',enemies:[['山賊',7,1,'fighter'],['山賊',8,3,'fighter'],['傭兵',6,5,'sword'],['ガザック',8,6,'boss']]},
 {title:'霧深き古城',roman:'II',story:'森を抜けた一行は、霧に閉ざされた古城へ辿り着く。捕らわれた司祭を救い、城門を突破せよ。',objective:'城門の将を撃破',terrain:'forest',enemies:[['帝国兵',8,1,'lance'],['弓兵',6,2,'archer'],['帝国兵',7,5,'lance'],['魔道士',5,6,'mage'],['門将バルガス',8,6,'boss']]},
 {title:'王都奪還',roman:'III',story:'ついに王都セレネへ。玉座を穢す黒騎士を討ち、奪われた祖国の光を取り戻せ。',objective:'黒騎士ヴァルドを撃破',terrain:'castle',enemies:[['重装兵',6,1,'armor'],['魔道士',8,1,'mage'],['弓兵',5,3,'archer'],['重装兵',7,5,'armor'],['黒騎士ヴァルド',8,6,'boss']]}
];
const heroesBase=[['アルド','ロード','⚔',1,0,'銀の剣'],['ミレイユ','ペガサス','♞',1,2,'細身の槍'],['ボルス','戦士','♜',0,4,'鋼の斧'],['セラ','僧侶','✦',1,6,'癒しの杖']];
const terrainInfo={plain:['平原',0,0],forest:['森',20,1],mountain:['山',30,1],water:['河川',0,0],fort:['砦',20,2],wall:['城壁',0,3]};
let stage=0,turn=1,phase='player',selected=null,moveTiles=[],units=[],busy=false;
const $=s=>document.querySelector(s), battlefield=$('#battlefield');
function makeUnit(data,team,i){const isHero=team==='ally';return {name:data[0],class:isHero?data[1]:(data[3]==='boss'?'将軍':'帝国兵'),icon:isHero?data[2]:iconFor(data[3]),x:isHero?data[3]:data[1],y:isHero?data[4]:data[2],weapon:isHero?data[5]:weaponFor(data[3]),team,level:isHero?stage+1:(stage+2),maxHp:isHero?18+i*3+stage*2:(data[3]==='boss'?28+stage*5:14+stage*3),hp:0,str:isHero?7+i:6+stage+i,def:isHero?4+i:3+stage,spd:isHero?7-i:4+stage,move:isHero?3:2,acted:false,type:data[3]};}
function iconFor(t){return ({fighter:'♟',sword:'†',boss:'♛',lance:'♟',archer:'➶',mage:'✦',armor:'♜'})[t]||'♟'}function weaponFor(t){return ({fighter:'鉄の斧',sword:'鉄の剣',boss:'暗黒の剣',lance:'鋼の槍',archer:'長弓',mage:'炎の魔道書',armor:'鋼の槍'})[t]}
function startStage(n){stage=n;turn=1;phase='player';selected=null;busy=false;const heroes=heroesBase.map((h,i)=>makeUnit(h,'ally',i));const foes=stages[n].enemies.map((e,i)=>makeUnit(e,'enemy',i));units=[...heroes,...foes];units.forEach(u=>u.hp=u.maxHp);updateChapter();render();showPhase('PLAYER','あなたの軍勢');}
function updateChapter(){const s=stages[stage];$('#stageNo').textContent=`STAGE 0${stage+1}`;$('#stageTitle').textContent=s.title;$('#stageStory').textContent=s.story;$('#objectiveText').textContent=s.objective;$('#chapterRoman').textContent=s.roman;$('#turnNumber').textContent=turn;document.querySelectorAll('.chapter-tab').forEach((t,i)=>{t.classList.toggle('active',i===stage);t.classList.toggle('locked',i>stage)});}
function tileType(x,y){if(stages[stage].terrain==='forest'){if([[3,0],[4,0],[3,1],[1,4],[2,4],[4,5],[4,6]].some(p=>p[0]===x&&p[1]===y))return'forest';if(x===9)return'wall';if(x===8&&y===6)return'fort'}else if(stages[stage].terrain==='castle'){if(x===4||x===9)return'wall';if(x>4&&y===0||x>4&&y===7)return'wall';if(x===8&&y===6)return'fort'}else{if(y===2&&x>1&&x<6)return'water';if([[3,0],[4,0],[4,4],[5,4]].some(p=>p[0]===x&&p[1]===y))return'forest';if([[7,0],[8,0],[6,6]].some(p=>p[0]===x&&p[1]===y))return'mountain';if(x===8&&y===6)return'fort'}return'plain'}
function render(){battlefield.innerHTML='';for(let y=0;y<8;y++)for(let x=0;x<10;x++){const t=document.createElement('button'),type=tileType(x,y);t.className=`tile ${type}`;t.dataset.x=x;t.dataset.y=y;t.setAttribute('aria-label',`${x+1},${y+1} ${terrainInfo[type][0]}`);if(moveTiles.some(p=>p.x===x&&p.y===y))t.classList.add('move');if(selected&&selected.team==='ally'&&units.some(u=>u.team==='enemy'&&u.x===x&&u.y===y&&distance(u,selected)===1))t.classList.add('attack');const u=unitAt(x,y);if(u){const d=document.createElement('div');d.className=`unit ${u.team==='enemy'?'enemy':''} ${u.acted?'acted':''}`;d.innerHTML=`${u.icon}<span class="unit-badge">${u.level}</span><span class="hp"><i style="width:${u.hp/u.maxHp*100}%"></i></span>`;t.appendChild(d)}t.onclick=()=>clickTile(x,y,type);t.onmouseenter=()=>showTerrain(type);battlefield.appendChild(t)}updateParty();if(selected)showUnit(selected);else hideUnit()}
function clickTile(x,y,type){if(busy||phase!=='player')return;const u=unitAt(x,y);if(selected){if(u&&u.team==='enemy'&&distance(u,selected)===1){combat(selected,u);return}if(moveTiles.some(p=>p.x===x&&p.y===y)&&!u){selected.x=x;selected.y=y;moveTiles=[];log(`${selected.name}が移動しました。隣接する敵を攻撃できます。`);render();return}}if(u&&u.team==='ally'&&!u.acted){selected=u;moveTiles=reachable(u);log(`${u.name}を選択。移動先を選んでください。`);render()}else if(!u){selected=null;moveTiles=[];render()}showTerrain(type)}
function reachable(u){const a=[];for(let y=0;y<8;y++)for(let x=0;x<10;x++){const d=Math.abs(x-u.x)+Math.abs(y-u.y),type=tileType(x,y);if(d>0&&d<=u.move&&!['water','wall'].includes(type)&&!unitAt(x,y))a.push({x,y})}return a}
async function combat(a,d){busy=true;a.acted=true;openCombatScene(a,d);const damage=Math.max(2,a.str+d.level-d.def);await animateAttack(a,d,damage);d.hp-=damage;updateCombatHp(a,d);log(`${a.name}の攻撃！ ${d.name}に ${damage} ダメージ。`);if(d.hp<=0){await finishBlow(d);units=units.filter(u=>u!==d);log(`${d.name}を撃破した！`)}else if(distance(a,d)===1){await wait(350);const counter=Math.max(1,d.str-a.def);await animateAttack(d,a,counter);a.hp-=counter;updateCombatHp(a,d);log(`${d.name}の反撃！ ${a.name}に ${counter} ダメージ。`);if(a.hp<=0){await finishBlow(a);units=units.filter(u=>u!==a)}}await wait(500);closeCombatScene();selected=null;moveTiles=[];busy=false;render();autoSave();if(checkResult())return;if(units.filter(u=>u.team==='ally').every(u=>u.acted))endPlayerTurn()}
function endPlayerTurn(){if(busy||phase!=='player')return;phase='enemy';selected=null;moveTiles=[];$('#phaseLabel').textContent='ENEMY PHASE';showPhase('ENEMY','帝国軍の進撃',true);render();setTimeout(enemyTurn,900)}
async function enemyTurn(){busy=true;const enemies=units.filter(u=>u.team==='enemy');for(const e of enemies){if(!units.includes(e))continue;const targets=units.filter(u=>u.team==='ally');if(!targets.length)break;targets.sort((a,b)=>distance(e,a)-distance(e,b));const t=targets[0];if(distance(e,t)>1){const dx=Math.sign(t.x-e.x),dy=Math.sign(t.y-e.y);let nx=e.x+(Math.abs(t.x-e.x)>=Math.abs(t.y-e.y)?dx:0),ny=e.y+(Math.abs(t.x-e.x)<Math.abs(t.y-e.y)?dy:0);if(nx>=0&&nx<10&&ny>=0&&ny<8&&!unitAt(nx,ny)&&!['water','wall'].includes(tileType(nx,ny))){e.x=nx;e.y=ny;render();await wait(220)}}if(distance(e,t)===1){const dmg=Math.max(1,e.str-t.def);openCombatScene(t,e);await animateAttack(e,t,dmg);t.hp-=dmg;updateCombatHp(t,e);log(`${e.name}の攻撃！ ${t.name}に ${dmg} ダメージ。`);if(t.hp<=0){await finishBlow(t);units=units.filter(u=>u!==t)}await wait(400);closeCombatScene();render()}}busy=false;if(checkResult())return;turn++;phase='player';units.filter(u=>u.team==='ally').forEach(u=>u.acted=false);$('#turnNumber').textContent=turn;$('#phaseLabel').textContent='PLAYER PHASE';showPhase('PLAYER','あなたの軍勢');render();autoSave()}
function checkResult(){const allies=units.filter(u=>u.team==='ally'),enemies=units.filter(u=>u.team==='enemy');if(!allies.length){setTimeout(()=>{alert('敗北しました。章をやり直します。');startStage(stage)},300);return true}const bossAlive=enemies.some(e=>e.type==='boss');if(!enemies.length||(stage>0&&!bossAlive)){busy=true;$('#resultTitle').textContent=stages[stage].title+' 制圧';$('#nextStage').textContent=stage<2?'次の章へ進む  ›':'エンディングを見る  ›';$('#resultModal').hidden=false;return true}return false}
function showUnit(u){$('#unitEmpty').hidden=true;$('#unitCard').hidden=false;$('#unitPortrait').textContent=u.icon;$('#unitName').textContent=u.name;$('#unitClass').textContent=u.class;$('#unitLevel').textContent=u.level;$('#hpText').textContent=`${Math.max(0,u.hp)}/${u.maxHp}`;$('#hpBar').style.width=`${Math.max(0,u.hp)/u.maxHp*100}%`;$('#unitWeapon').textContent=u.weapon;$('#weaponMight').textContent=`威力 ${u.str} / 射程 1`;$('#unitStats').innerHTML=[['力',u.str],['守備',u.def],['速さ',u.spd],['移動',u.move]].map(s=>`<div class="stat"><span>${s[0]}</span><b>${s[1]}</b></div>`).join('');$('#unitGuide').textContent=u.team==='ally'?(u.acted?'行動終了':'青いマスを選択して移動'):'敵軍ユニット'}function hideUnit(){$('#unitEmpty').hidden=false;$('#unitCard').hidden=true}
function updateParty(){$('#partyList').innerHTML=units.filter(u=>u.team==='ally').map(u=>`<div class="party-mini"><span class="mini-face">${u.icon}</span><b>${u.name}</b><i>HP ${Math.max(0,u.hp)}/${u.maxHp}</i></div>`).join('')}
function showTerrain(t){const d=terrainInfo[t];$('#terrainName').textContent=d[0];$('#terrainAvoid').textContent=`+${d[1]}`;$('#terrainDef').textContent=`+${d[2]}`}
function showPhase(name,sub,enemy=false){const b=$('#phaseBanner');b.className=`phase-banner ${enemy?'enemy-phase':''}`;b.innerHTML=`<small>PHASE</small><strong>${name}</strong><span>${sub}</span>`;void b.offsetWidth}
function openCombatScene(ally,enemy){$('#combatScene').hidden=false;$('#combatAllyName').textContent=ally.name;$('#combatAllyIcon').textContent=ally.icon;$('#combatEnemyName').textContent=enemy.name;$('#combatEnemyIcon').textContent=enemy.icon;updateCombatHp(ally,enemy);$('#combatCaption').textContent=`${ally.name}　対　${enemy.name}`}
function updateCombatHp(ally,enemy){$('#combatAllyHp').style.width=`${Math.max(0,ally.hp)/ally.maxHp*100}%`;$('#combatEnemyHp').style.width=`${Math.max(0,enemy.hp)/enemy.maxHp*100}%`;$('#combatAllyHpText').textContent=`HP ${Math.max(0,ally.hp)} / ${ally.maxHp}`;$('#combatEnemyHpText').textContent=`HP ${Math.max(0,enemy.hp)} / ${enemy.maxHp}`}
async function animateAttack(attacker,defender,damage){const scene=$('#combatScene'),attackerSide=attacker.team==='ally'?'ally':'enemy',defenderSide=defender.team==='ally'?'ally':'enemy';$('#combatCaption').textContent=`${attacker.name}の攻撃！`;scene.className=`combat-scene attacking-${attackerSide}`;await wait(300);scene.className=`combat-scene slashing hit-${defenderSide}`;$('#damageNumber').textContent=`-${damage}`;$('#damageNumber').style.left=defenderSide==='ally'?'23%':'70%';void scene.offsetWidth;await wait(180);scene.classList.add('show-damage');await wait(600);scene.className='combat-scene'}
async function finishBlow(unit){$('#combatCaption').textContent=`${unit.name}を撃破！`;await wait(550)}function closeCombatScene(){$('#combatScene').hidden=true;$('#combatScene').className='combat-scene'}
const SAVE_KEY='flame-emblem-save-v1';
function saveGame(silent=false){if(busy&&!silent){log('戦闘中は記録できません。');return}const data={version:1,stage,turn,phase:phase==='enemy'?'player':phase,units,updatedAt:new Date().toISOString()};localStorage.setItem(SAVE_KEY,JSON.stringify(data));updateLoadButton();if(!silent){log(`第${stage+1}章・${turn}ターン目を記録しました。`);$('#saveGame').classList.add('save-toast');setTimeout(()=>$('#saveGame').classList.remove('save-toast'),600)}}
function autoSave(){saveGame(true)}
function loadGame(){if(busy)return;try{const data=JSON.parse(localStorage.getItem(SAVE_KEY));if(!data||data.version!==1||!Array.isArray(data.units))throw new Error();stage=data.stage;turn=data.turn;phase='player';units=data.units;units.filter(u=>u.team==='ally').forEach(u=>u.acted=false);selected=null;moveTiles=[];busy=false;$('#resultModal').hidden=true;$('#phaseLabel').textContent='PLAYER PHASE';updateChapter();render();showPhase('PLAYER','記録から再開');log(`第${stage+1}章・${turn}ターン目の記録を読み込みました。`)}catch(e){localStorage.removeItem(SAVE_KEY);updateLoadButton();log('読み込める記録がありません。')}}
function updateLoadButton(){$('#loadGame').disabled=!localStorage.getItem(SAVE_KEY)}
function unitAt(x,y){return units.find(u=>u.x===x&&u.y===y)}function distance(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y)}function log(s){$('#messageLog').textContent=s}function wait(ms){return new Promise(r=>setTimeout(r,ms))}
$('#saveGame').onclick=()=>saveGame();$('#loadGame').onclick=loadGame;$('#endTurn').onclick=endPlayerTurn;$('#nextStage').onclick=()=>{if(stage<2){$('#resultModal').hidden=true;startStage(stage+1);autoSave()}else{alert('王都に光が戻った—— 完。');localStorage.removeItem(SAVE_KEY);$('#resultModal').hidden=true;startStage(0);updateLoadButton()}};document.querySelectorAll('.chapter-tab').forEach(t=>t.onclick=()=>{const n=+t.dataset.stage;if(n<=stage){$('#resultModal').hidden=true;startStage(n)}});startStage(0);updateLoadButton();
